import {
  FiAlertCircle,
  FiActivity,
  FiBarChart2,
  FiCalendar,
  FiChevronLeft,
  FiClipboard,
  FiClock,
  FiCreditCard,
  FiDatabase,
  FiGlobe,
  FiGrid,
  FiHelpCircle,
  FiHome,
  FiImage,
  FiMenu,
  FiMoon,
  FiSettings,
  FiShield,
  FiSlash,
  FiSun,
  FiUsers,
  FiUser,
} from "react-icons/fi";
import { LuPhilippinePeso } from "react-icons/lu";

export const icons = {
  actionLogs: FiActivity,
  alert: FiAlertCircle,
  availability: FiClock,
  blockedSlots: FiSlash,
  calendar: FiCalendar,
  collapse: FiChevronLeft,
  dashboard: FiGrid,
  faq: FiHelpCircle,
  gallery: FiImage,
  history: FiClock,
  home: FiHome,
  management: FiSettings,
  menu: FiMenu,
  moon: FiMoon,
  payment: FiCreditCard,
  storage: FiDatabase,
  rates: LuPhilippinePeso,
  reports: FiBarChart2,
  reservations: FiCalendar,
  roles: FiShield,
  rules: FiClipboard,
  settings: FiSettings,
  site: FiGlobe,
  staff: FiUsers,
  sun: FiSun,
  user: FiUser,
} as const;
